<!DOCTYPE html>
<html>

<head>
    <title>Internal Receipt - {{ $invoice->receipt_number }}</title>
    <style>
        body {
            font-family: sans-serif;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .details {
            margin-bottom: 20px;
        }

        .footer {
            margin-top: 50px;
            font-size: 12px;
            text-align: center;
            color: #666;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #ccc;
            padding: 10px;
            text-align: left;
        }

        .amount {
            font-weight: bold;
            font-size: 18px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Internal Payment Receipt</h1>
        <p>Receipt No: {{ $invoice->receipt_number }}</p>
    </div>

    <div class="details">
        <p><strong>Date:</strong> {{ $invoice->payment_received_date }}</p>
        <p><strong>Customer:</strong> {{ $invoice->customer->name }}</p>
        <p><strong>Invoice Number:</strong> {{ $invoice->invoice_number }}</p>
        <p><strong>PO Number:</strong> {{ $invoice->purchaseOrder->po_number }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Cheque Number</td>
                <td>{{ $invoice->cheque_number }}</td>
            </tr>
            <tr>
                <td>Issuing Bank</td>
                <td>{{ $invoice->bank_name }}</td>
            </tr>
            <tr>
                <td>Payment Amount</td>
                <td class="amount">${{ number_format($invoice->payment_amount, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Finance System on {{ date('Y-m-d H:i:s') }}</p>
        <p>This is a computer-generated document. No signature required.</p>
    </div>
</body>

</html>